import React from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useDashboardStore } from '../store/dashboardStore'

export default function CityCatalogueDetail() {
  const { catalogueId } = useParams()
  const navigate = useNavigate()
  const { cityCatalogues, cityCatalogueTestMappings, partners } = useDashboardStore()

  const catalogue = cityCatalogues.find((c) => c.id === catalogueId)
  const mappedTests = cityCatalogueTestMappings.filter((m) => m.catalogueId === catalogueId)

  const getPartnerName = (partnerId) => partners.find((p) => p.id === partnerId)?.name || '—'

  if (!catalogue) {
    return (
      <>
        <header className="main-header">
          <h2 className="page-title">Catalogue Not Found</h2>
        </header>
        <div className="content">
          <section className="panel">
            <div className="panel-body">
              <div className="test-catalog-empty">
                <span>❌</span>
                <p>The requested catalogue could not be found.</p>
                <button onClick={() => navigate('/city-catalogues')} className="btn-primary" style={{ marginTop: '1rem' }}>
                  Back to Catalogues
                </button>
              </div>
            </div>
          </section>
        </div>
      </>
    )
  }

  const isAutoGenerated = catalogue.id.startsWith('ctlg_auto_')

  return (
    <>
      <header className="main-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '0.5rem' }}>
          <button
            onClick={() => navigate('/city-catalogues')}
            className="btn-secondary"
            style={{ padding: '0.5rem 1rem' }}
          >
            ← Back
          </button>
          <h2 className="page-title" style={{ margin: 0 }}>{catalogue.name}</h2>
          {isAutoGenerated && (
            <span style={{
              fontSize: '0.875rem',
              background: '#dbeafe',
              color: '#1e40af',
              padding: '0.25rem 0.75rem',
              borderRadius: '6px',
              fontWeight: 600
            }}>
              🤖 AUTO-GENERATED
            </span>
          )}
        </div>
        <p className="page-desc">
          {catalogue.city}, {catalogue.state} • {mappedTests.length} test{mappedTests.length !== 1 ? 's' : ''} mapped
        </p>
      </header>

      <div className="content">
        <section className="panel">
          <div className="panel-header">
            <h3 className="panel-title">Mapped Tests</h3>
          </div>
          <div className="panel-body">
            {mappedTests.length === 0 ? (
              <div className="test-catalog-empty">
                <span>📋</span>
                <p>No tests mapped to this catalogue yet.</p>
              </div>
            ) : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Test Code</th>
                      <th>Test Name</th>
                      <th>Category</th>
                      <th>Partner</th>
                      <th>Status</th>
                      <th>Source</th>
                    </tr>
                  </thead>
                  <tbody>
                    {mappedTests.map((mapping) => {
                      const isAutoMapping = mapping.id.startsWith('ctm_auto_')
                      return (
                        <tr key={mapping.id}>
                          <td>
                            <code className="test-code-badge">{mapping.testCode}</code>
                          </td>
                          <td style={{ fontWeight: 500 }}>{mapping.testName}</td>
                          <td>{mapping.category}</td>
                          <td>{getPartnerName(mapping.partnerId)}</td>
                          <td>
                            <span className={`status-badge ${mapping.status === 'active' ? 'status-active' : 'status-inactive'}`}>
                              {mapping.status?.toUpperCase()}
                            </span>
                          </td>
                          <td style={{ fontSize: '0.82rem', color: '#666' }}>
                            {isAutoMapping ? '🤖 Auto-generated' : '👤 Manual'}
                          </td>
                        </tr>
                      )
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </section>
      </div>
    </>
  )
}

