import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useDashboardStore } from '../store/dashboardStore'
import { INDIAN_STATES } from '../data/indiaLocations'

export default function CityCatalogue() {
  const navigate = useNavigate()
  const {
    cityCatalogues,
    cityCatalogueTestMappings,
  } = useDashboardStore()

  // Filters for view tab
  const [stateFilter, setStateFilter] = useState('')
  const [searchQuery, setSearchQuery] = useState('')

  // Get test count for each catalogue
  const getCatalogueTestCount = (catalogueId) => {
    return cityCatalogueTestMappings.filter((m) => m.catalogueId === catalogueId).length
  }

  // Filter catalogues based on search and state filter
  const filteredCatalogues = cityCatalogues.filter(catalogue => {
    const matchesState = !stateFilter || catalogue.state === stateFilter
    const matchesSearch = !searchQuery ||
      catalogue.name?.toLowerCase().includes(searchQuery.toLowerCase()) ||
      catalogue.city?.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesState && matchesSearch
  })

  return (
    <>
      <header className="main-header">
        <h2 className="page-title">City Catalogues (Auto-Generated)</h2>
        <p className="page-desc">
          📋 City catalogues are automatically created when tests are mapped to collection centers.
          View and monitor auto-generated catalogues and test mappings below.
        </p>
      </header>
      <div className="content">
        <section className="panel">
          <div className="panel-header">
            <h3 className="panel-title">City Catalogues</h3>
          </div>
          <div className="panel-body">
              {/* Info Banner */}
              <div style={{
                padding: '1rem',
                background: '#f0f9ff',
                border: '1px solid #0ea5e9',
                borderRadius: '8px',
                marginBottom: '1.5rem'
              }}>
                <div style={{ fontWeight: 600, color: '#0369a1', marginBottom: '0.5rem' }}>
                  🤖 Automated City Catalogues
                </div>
                <div style={{ fontSize: '0.9rem', color: '#075985' }}>
                  City catalogues are automatically created when you map tests to collection centers.
                  Each city gets its own catalogue, and tests are automatically added to the appropriate catalogue based on the center's location.
                </div>
              </div>
            {/* Filters */}
            <div className="test-catalog-filters" style={{ marginBottom: '1rem' }}>
              <input
                type="text"
                placeholder="Search by catalogue name or city…"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                style={{ flex: 1, minWidth: '200px' }}
              />
              <select
                value={stateFilter}
                onChange={(e) => setStateFilter(e.target.value)}
                style={{ minWidth: '220px' }}
              >
                <option value="">All States</option>
                {INDIAN_STATES.map((state) => (
                  <option key={state} value={state}>{state}</option>
                ))}
              </select>
            </div>

            {cityCatalogues.length === 0 ? (
              <div className="test-catalog-empty">
                <span>📚</span>
                <p>No city catalogues found. Map tests to collection centers to auto-generate catalogues.</p>
              </div>
            ) : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Catalogue Name</th>
                      <th>State</th>
                      <th>City</th>
                      <th>Test Count</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {filteredCatalogues.length === 0 ? (
                      <tr>
                        <td colSpan="5" style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                          No catalogues found matching your filters.
                        </td>
                      </tr>
                    ) : (
                      filteredCatalogues.map((c) => {
                        const isAutoGenerated = c.id.startsWith('ctlg_auto_')
                        return (
                          <tr key={c.id}>
                            <td>
                              <span
                                onClick={() => navigate(`/city-catalogues/${c.id}`)}
                                style={{
                                  cursor: 'pointer',
                                  color: 'var(--accent)',
                                  fontWeight: 600,
                                  textDecoration: 'none',
                                  transition: 'all 0.2s ease'
                                }}
                                onMouseEnter={(e) => e.target.style.textDecoration = 'underline'}
                                onMouseLeave={(e) => e.target.style.textDecoration = 'none'}
                              >
                                {c.name}
                              </span>
                              {isAutoGenerated && (
                                <span style={{
                                  marginLeft: '0.5rem',
                                  fontSize: '0.75rem',
                                  background: '#dbeafe',
                                  color: '#1e40af',
                                  padding: '0.125rem 0.375rem',
                                  borderRadius: '4px',
                                  fontWeight: 600
                                }}>
                                  🤖 AUTO
                                </span>
                              )}
                            </td>
                            <td>{c.state}</td>
                            <td>{c.city}</td>
                            <td>
                              <span style={{
                                fontWeight: 600,
                                color: 'var(--primary)',
                                background: '#fef2f2',
                                padding: '0.25rem 0.5rem',
                                borderRadius: '4px'
                              }}>
                                {getCatalogueTestCount(c.id)} tests
                              </span>
                            </td>
                            <td>
                              <span className={`status-badge ${c.status === 'active' ? 'status-active' : 'status-inactive'}`}>
                                {c.status?.toUpperCase()}
                              </span>
                            </td>
                          </tr>
                        )
                      })
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </section>
      </div>
    </>
  )
}
